/*
Copyright Ishtiaq Islam.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	crdcomv1 "github.com/ishtiaqhimel/crd/pkg/apis/crd.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSakiibBhais implements SakiibBhaiInterface
type FakeSakiibBhais struct {
	Fake *FakeCrdV1
	ns   string
}

var sakiibbhaisResource = schema.GroupVersionResource{Group: "crd.com", Version: "v1", Resource: "sakiibbhais"}

var sakiibbhaisKind = schema.GroupVersionKind{Group: "crd.com", Version: "v1", Kind: "SakiibBhai"}

// Get takes name of the sakiibBhai, and returns the corresponding sakiibBhai object, and an error if there is any.
func (c *FakeSakiibBhais) Get(ctx context.Context, name string, options v1.GetOptions) (result *crdcomv1.SakiibBhai, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sakiibbhaisResource, c.ns, name), &crdcomv1.SakiibBhai{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.SakiibBhai), err
}

// List takes label and field selectors, and returns the list of SakiibBhais that match those selectors.
func (c *FakeSakiibBhais) List(ctx context.Context, opts v1.ListOptions) (result *crdcomv1.SakiibBhaiList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sakiibbhaisResource, sakiibbhaisKind, c.ns, opts), &crdcomv1.SakiibBhaiList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdcomv1.SakiibBhaiList{ListMeta: obj.(*crdcomv1.SakiibBhaiList).ListMeta}
	for _, item := range obj.(*crdcomv1.SakiibBhaiList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sakiibBhais.
func (c *FakeSakiibBhais) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sakiibbhaisResource, c.ns, opts))

}

// Create takes the representation of a sakiibBhai and creates it.  Returns the server's representation of the sakiibBhai, and an error, if there is any.
func (c *FakeSakiibBhais) Create(ctx context.Context, sakiibBhai *crdcomv1.SakiibBhai, opts v1.CreateOptions) (result *crdcomv1.SakiibBhai, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sakiibbhaisResource, c.ns, sakiibBhai), &crdcomv1.SakiibBhai{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.SakiibBhai), err
}

// Update takes the representation of a sakiibBhai and updates it. Returns the server's representation of the sakiibBhai, and an error, if there is any.
func (c *FakeSakiibBhais) Update(ctx context.Context, sakiibBhai *crdcomv1.SakiibBhai, opts v1.UpdateOptions) (result *crdcomv1.SakiibBhai, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sakiibbhaisResource, c.ns, sakiibBhai), &crdcomv1.SakiibBhai{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.SakiibBhai), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSakiibBhais) UpdateStatus(ctx context.Context, sakiibBhai *crdcomv1.SakiibBhai, opts v1.UpdateOptions) (*crdcomv1.SakiibBhai, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sakiibbhaisResource, "status", c.ns, sakiibBhai), &crdcomv1.SakiibBhai{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.SakiibBhai), err
}

// Delete takes name of the sakiibBhai and deletes it. Returns an error if one occurs.
func (c *FakeSakiibBhais) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(sakiibbhaisResource, c.ns, name, opts), &crdcomv1.SakiibBhai{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSakiibBhais) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sakiibbhaisResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &crdcomv1.SakiibBhaiList{})
	return err
}

// Patch applies the patch and returns the patched sakiibBhai.
func (c *FakeSakiibBhais) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crdcomv1.SakiibBhai, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sakiibbhaisResource, c.ns, name, pt, data, subresources...), &crdcomv1.SakiibBhai{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.SakiibBhai), err
}
